name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Issue' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: Download Assets
      # You may pin to the exact commit or the version.
      # uses: i3h/download-release-asset@a987f9dc3559bd1024d7ed353b59c9d0bbb8ab61
      uses: i3h/download-release-asset@v1.3.3
      with:
        # 
        owner: anabasis-dev 
        # 
        repo: anabasis-dev/apps
        # 
        tag: latest
        # 
        file: package.msi
        # 
        path: ./packages # optional
        # 
        token: ${{ secrets.GITHUB_TOKEN}}  # optional
